app/models/artist.rb, app/models/chatroom.rb, app/models/label.rb, app/models/user.rb
=> Added associations

Gemfile.lock, app/models/user.rb, db/seeds.rb
seeds for users created - 2 users
one artist and one label created
added dependent destroy to user model
@cvillen or @silsc please review and merge
=> seeds created, adds dependent destroy relationship

db/seeds.rb
seed messages created @silsc or @cvillen
=> seed messages added

app/controllers/artists_controller.rb, config/routes.rb, test/controllers/artists_controller_test.rb
Added artist routes and controller actions
=> artist routes and controller actions added

app/controllers/labels_controller.rb, config/routes.rb, test/controllers/labels_controller_test.rb
=> label controller actions and routes added

app/controllers/pages_controller.rb, config/routes.rb
added styleguide to pages routes and controller
created styleguide view
=> added styleguide to pages

app/channels/chatroom_channel.rb, app/javascript/channels/chatroom_channel.js, app/javascript/packs/application.js, app/views/chatrooms/show.html.erb, app/views/messages/_messages.html.erb, test/channels/chatroom_channel_test.rb
+++ STILL MISSING TO MAKE IT WORK BETWEEN USERS
=> added chatroom channel and JS

app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/config/_fonts.scss, app/assets/stylesheets/pages/_styleguide.scss, app/views/pages/styleguide.html.erb
Imported fonts to the configuration
=> Added fonts

app/assets/stylesheets/pages/_styleguide.scss, app/views/pages/styleguide.html.erb
added buttons style on the styleguide
=> added buttons style

app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/pages/_styleguide.scss, app/views/pages/styleguide.html.erb
Added color scheme to the configuration
=> Config colorscheme

app/controllers/artists_controller.rb, app/controllers/labels_controller.rb, app/models/artist.rb, app/views/artists/new.html.erb, app/views/artists/show.html.erb, db/migrate/20210615155416_change_genre_influences.rb, db/schema.rb, db/seeds.rb
Added artist view with create and edit action fully functional.
=> Artist views

db/migrate/20210616083001_add_roles_to_artist.rb, db/schema.rb
added roles to the artist table
=> added roles to the artist table

app/assets/stylesheets/pages/_styleguide.scss, app/views/pages/styleguide.html.erb
added basic card for the artist profile
=> styled basic card

app/views/artists/show.html.erb
Added dynamic tabs for links, songs and events.
=> Artist profile tabs

app/models/user.rb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb
styled sign-up and login forms
added checkbox
=> Sign up form

app/controllers/application_controller.rb, app/views/devise/registrations/new.html.erb, app/views/pages/home.html.erb
Sign up as Artist
Sign up as Label
=> Sign up path as user or label set

app/controllers/labels_controller.rb, app/views/artists/new.html.erb, app/views/artists/show.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/registrations/edit.html.erb, app/views/labels/new.html.erb, app/views/labels/show.html.erb
styled forms for create new artist and login
=> Forms style

app/assets/stylesheets/pages/_styleguide.scss, app/views/pages/styleguide.html.erb
Added tabs html to the styleguide file.
=> Styleguide tabs

app/controllers/application_controller.rb, app/controllers/pages_controller.rb, app/lib/my_failure_app.rb, app/views/pages/redirect.html.erb, config/initializers/devise.rb, config/routes.rb
Added redirect sign up page non styled
=> added redirect sign up page

app/assets/stylesheets/application.scss
fixed import scss syntax error
=> fixed import scss syntax error

app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_styleguide.scss, app/views/pages/home.html.erb
moved footer to home removed extra padding
=> moved footer to home, removed extra padding

app/views/pages/home.html.erb
added correct path to Join us, Get started and Sign up buttons
-added margin-right to divide buttons
=> Redirect path

app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb, app/views/pages/styleguide.html.erb
=> Style landing page

app/assets/stylesheets/application.scss, app/assets/stylesheets/vendor/_calendar.scss, app/javascript/controllers/calendar_controller.js, app/javascript/vendor/caleandar.js, app/views/layouts/application.html.erb, app/views/pages/styleguide.html.erb, app/views/shared/_calendar.html.erb
created vendor maps in styleguides and JS to implement caleandar logic
styled calendar based on figma colors
starded creating JS logic
=> calendar added to styleguides

.gitignore, Gemfile, Gemfile.lock, app/controllers/artists_controller.rb, app/models/artist.rb, app/views/artists/new.html.erb, config/environments/development.rb, config/storage.yml, db/migrate/20210617135231_create_active_storage_tables.active_storage.rb, db/schema.rb
Cloudinary setup and artist add photo
=> Cloudinary setup

app/controllers/labels_controller.rb, app/models/label.rb, app/views/labels/new.html.erb
=> added photo to label new form

app/assets/stylesheets/application.scss, app/assets/stylesheets/artists/_show.scss, app/views/artists/show.html.erb
Created modals for each card and tabs.
Changed "edit" buttons for icons instead.
=> Artist profile modals

db/migrate/20210617152132_add_title_to_songs.rb, db/schema.rb
=> added columns to songs

app/controllers/artists_controller.rb, app/controllers/songs_controller.rb, app/models/song.rb, app/views/artists/show.html.erb
=> added song player

app/assets/stylesheets/artists/_show.scss, app/views/artists/show.html.erb
added example Instagram photos to Artist profile
=> hardcoded Instagram opictures

app/assets/stylesheets/artists/_show.scss, app/views/artists/show.html.erb
=> added song cards

app/views/pages/home.html.erb
=> card styling done

app/views/artists/show.html.erb
Added margin top to the Instagram h4.
=> Added margin top to Instagram h4.

app/views/artists/show.html.erb
=> Add missing upload line

config/environments/production.rb
=> cloudinary production

app/assets/stylesheets/pages/_home.scss
fixed style on the landing page
=> fixed style landing

app/assets/stylesheets/labels/_index.scss, app/assets/stylesheets/labels/_show.scss, app/views/labels/show.html.erb
styled label profile page done
=> styled label profile page

.gitignore, app/assets/stylesheets/vendor/_calendar.scss, app/controllers/api/v1/base_controller.rb, app/controllers/api/v1/events_controller.rb, app/controllers/artists/events_controller.rb, app/controllers/artists_controller.rb, app/controllers/events_controller.rb, app/javascript/controllers/calendar_controller.js, app/models/artist.rb, app/models/event.rb, app/views/api/v1/events/index.json.jbuilder, app/views/api/v1/events/show.json.jbuilder, app/views/artists/show.html.erb, app/views/events/_new.html.erb, app/views/shared/_calendar.html.erb, config/routes.rb, test/controllers/events_controller_test.rb
Created functional calendar with events, when you click on the date, the created event could be shown bellow
=> Events controller

app/assets/stylesheets/artists/_show.scss, app/views/artists/show.html.erb
Added iframes for youtube and instagram.
=> Artist profile view

app/assets/stylesheets/components/_card-events.scss, app/assets/stylesheets/components/_index.scss, app/controllers/artists/events_controller.rb, app/controllers/artists_controller.rb, app/controllers/events_controller.rb, app/controllers/labels_controller.rb, app/javascript/controllers/calendar_controller.js, app/javascript/vendor/caleandar.js, app/views/events/_event_card.html.erb, app/views/labels/show.html.erb, app/views/shared/_calendar.html.erb, config/routes.rb
calendar functionality fully done
@flaviadteixeira, @cvillen, @silsc
=> Events label

app/controllers/chatrooms_controller.rb, app/javascript/packs/application.js, app/models/artist.rb, app/models/chatroom.rb, app/models/user.rb, app/views/artists/show.html.erb, app/views/chatrooms/index.html.erb, app/views/chatrooms/show.html.erb, app/views/labels/show.html.erb, config/routes.rb, db/migrate/20210621091330_add_users_to_chatroom.rb, db/schema.rb, db/seeds.rb
set up the chat for both labels and artists
updated the seeds
=> Chat setup

app/views/artists/show.html.erb, app/views/labels/show.html.erb
added the path to chatroom index
=> added the path to chatroom index

app/assets/stylesheets/application.scss, app/assets/stylesheets/chatrooms/_index.scss, app/controllers/chatrooms_controller.rb, app/views/artists/show.html.erb, app/views/chatrooms/index.html.erb
=> first style for chatroom

app/models/artist.rb, app/models/label.rb, app/models/song.rb, app/models/user.rb
=> Validations

app/controllers/application_controller.rb
after logging in, users are redirected to their profiles
=> adds path for log in

app/assets/stylesheets/chatrooms/_index.scss, app/assets/stylesheets/chatrooms/_show.scss, app/views/chatrooms/index.html.erb, app/views/chatrooms/show.html.erb
styled chatroom index and show in a simple way
=> Chat style index show

app/controllers/application_controller.rb, app/models/chatroom.rb, app/models/user.rb, app/views/chatrooms/index.html.erb, app/views/chatrooms/show.html.erb, db/seeds.rb
added other user names and pictures to chatroom show
=> Add chat info

app/views/chatrooms/index.html.erb
styled chatroom index view to match perfectly the show
=> styled index chatroom

app/assets/stylesheets/artists/_show.scss, app/controllers/artists_controller.rb, app/models/artist.rb, app/views/artists/_form.html.erb, app/views/artists/_form_fields.html.erb, app/views/artists/new.html.erb, app/views/artists/show.html.erb
Amended code to allow update influences and removed scroll bar from the card-links.
=> Artist profile show

app/controllers/application_controller.rb, db/seeds.rb
Fixed seeds 
Changed current_user to resources in the method in application controller
=> changed seeds and method in application controller

app/models/artist.rb, app/models/label.rb, app/models/user.rb, app/views/artists/show.html.erb, app/views/chatrooms/index.html.erb, app/views/labels/show.html.erb, app/views/shared/_navbar.html.erb
fixed the navbar
set user_type in the models
=> rendered navbar, set user_type

app/assets/stylesheets/components/_footer.scss, app/views/shared/_footer.html.erb
=> small footer icons styled

app/assets/stylesheets/chatrooms/_index.scss, app/assets/stylesheets/chatrooms/_show.scss, app/assets/stylesheets/config/_colors.scss, app/views/chatrooms/show.html.erb
Added some styling 
unfinished
=> changed colors

app/views/artists/show.html.erb
change from follow to connect
Unfollow to connected
=> changed button naming

app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb
=> updated navbar style

app/controllers/artists_controller.rb, app/controllers/labels_controller.rb, app/models/user.rb, app/views/artists/show.html.erb, app/views/labels/show.html.erb, config/cable.yml, config/routes.rb
label connections added @flaviadteixeira , @silsc or @cvillen please review and merge my request
=> Label connect

app/views/artists/_form_fields.html.erb, app/views/layouts/application.html.erb
Added style the autocomplete in the influences search filed.
=> Added style the autocomplete in the influences filed.

app/assets/stylesheets/results/_index.scss, app/views/results/index.html.erb
styled the search cards
links to profile are missing
=> styled the search cards

app/controllers/connections_controller.rb, app/models/connection.rb, app/models/user.rb, app/views/connections/index.html.erb, app/views/pages/home.html.erb, config/routes.rb
=> Connect sug

app/views/results/index.html.erb
added link profile
style missing (remove text decoration)
=> added link profile

app/views/artists/show.html.erb, app/views/labels/show.html.erb
=> fixed following

app/controllers/artists_controller.rb, app/controllers/labels_controller.rb, app/views/connections/index.html.erb
After creating profile we get connection suggestions
=> Connections path

app/assets/stylesheets/components/_avatar.scss, app/views/pages/redirect.html.erb
=> redirect style fixed

app/views/connections/index.html.erb
=> unconnect to remove

app/models/chatroom.rb
refactored get_others_users method
=> refactored get_others_users method

app/views/connections/index.html.erb
btn changed to blue for remove,
dsplay first3 artist, labels from seeds
=> remove btn blue

app/views/artists/show.html.erb, app/views/labels/show.html.erb
=> btn blue in profile

app/assets/stylesheets/results/_index.scss, app/views/artists/_form_fields.html.erb
Removed text decoration and kept same colour when hovering over <a> tags in the card-search.
=> Card search links

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_card-events.scss, app/assets/stylesheets/connections/_index.scss, app/views/connections/index.html.erb
=> styled the connections index

app/assets/stylesheets/chatrooms/_index.scss, app/assets/stylesheets/chatrooms/_show.scss
Removed text decoration and changed <a> tags colour to $primary20.
=> Removed text decoration and changed <a> tags colour to $primary20.

app/javascript/vendor/caleandar.js
=> added target blank to JS

app/assets/stylesheets/chatrooms/_index.scss, app/assets/stylesheets/chatrooms/_show.scss, app/views/chatrooms/show.html.erb
=> styled chat show

app/views/connections/index.html.erb
fixed margin and button in connections
=> fixed margin and button in connections

app/views/shared/_navbar.html.erb
logo leads to search for the moment
=> logo leads to search

app/assets/stylesheets/chatrooms/_show.scss, app/controllers/messages_controller.rb, app/views/chatrooms/show.html.erb
=> fixed and styled chatroom

app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_styleguide.scss, app/views/pages/home.html.erb
changed button and landing footer
=> changed button and landing footer

app/views/artists/show.html.erb, app/views/labels/show.html.erb
I can not message myself, only other labels or artists
=> message btn not in my profile

app/assets/stylesheets/artists/_show.scss, app/views/artists/show.html.erb
=> artist page styled

app/assets/stylesheets/results/_index.scss, app/javascript/controllers/filters_controller.js, app/views/results/index.html.erb
Added function to submit form by checking the checkboxes and added link to clear filters.
=> Checkbox form submit

app/assets/stylesheets/labels/_show.scss, app/views/labels/show.html.erb
=> styled label page

app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb
Styled banner landing and create a bit of responsiveness. Still not media queries added for smaller devices.
=> STYLE banner landing

app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb
Styled about section in the landing and added responsiveness. Still not responsive for smaller devices. Corrected some minor errors; footer is working properly.
=> STYLE about landing

app/views/pages/home.html.erb
Styled about section in the landing and added responsiveness. Still not responsive for smaller devices. Corrected some minor errors; footer is working properly.
=> STYLE/ deleted links footer landing
